baseURL: "https://teohxuen.github.io/website/" 
title: AUV Battery Management System
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Report
          url: report/
          weight: 2 
        - name: Guides
          url: guides/
          weight: 3
        - name: Specifications
          url: specifications/
          weight: 4


params:
    description: "Documentation of Bumblebee's AUV Battery Management System"
    author: Teoh Xu En
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["report", "guides", "specifications"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Battery Management System
          subtitle: "This Battery Management System is designed and tested for Bumblebee's AUV4.5 to be deployed at RoboSub 2025"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Report
              url: Report/
            - name: Guides
              url: Guides/
            - name: Specifications
              url: specifications/


    socialIcons:
        - name: GitHub
          url: https://github.com/pmichaillat


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Battery Management System"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2